# CloudiskServer 配置文件

# 服务器网络设置
ip = 0.0.0.0
# 控制连接端口
control_port = 8888
# 数据连接端口
data_port = 9999

# 最大并发连接数
max_connections = 10

# 上传文件的存储目录
upload_dir = /home/lichao/netdisk

# 线程池配置
thread_pool_size = 4 
task_queue_size = 10

# 数据库配置
db_host = localhost
db_user = root
db_pass = HunterX_007_L
db_name = cloudisk
